name: Declare and Print Variable

on: [push]

jobs:
  print-var-job:
    runs-on: windows-latest

    steps:
      - name: Declare variable
        run: |
          echo "MY_VAR=Hello from GitHub Actions" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Print variable
        run: |
          Write-Host "The value of MY_VAR is: $env:MY_VAR"
        shell: pwsh
