name: test-python
on: push
jobs:
    test-python:
        runs-on: windows-latest
        steps:
            - name: set conda env name
              run: |
                echo ENV_NAME=5 >> %GITHUB_ENV
              shell: pwsh
            - name: print env
              run: |
                Write-Host "value of env name is: $env:ENV_NAME"
              shell: pwsh
